### ISSUE TITLE
cannot complete distribution order

### ISSUE THREAD

**Issue by metas-lc** [metasfresh/metasfresh#1635]
### Is this a bug or feature request?
bug
### What is the current behavior?
you get an error when you want to complete distribution order
#### Which are the steps to reproduce?
1. swing, open distribution order window, create a new one
2. set all mandatory fields
3. add a line, complete 
=>  Terminated
https://pastebin.com/TrTctMMA
### What is the expected or desired behavior?
distribution order should complete

**Comment by teosarca** [comment]
Did a quick check. It seems the DD_Order.PP_Product_Planning_ID is expected to be set.
Also on a quick check i saw that the product planning is set when the DD order is generated.

**Comment by metas-ts** [comment]
> Did a quick check. It seems the DD_Order.PP_Product_Planning_ID is expected to be set.

yes, as of #523 it shall be set, mostly to improve transparency about what an auto-generated DD_Order is based on. I propobaly didn't think about the "manually generated DD_Order" case. In this case i guess we don't really need it.
I'll try to fix this one asap

**Comment by metas-ts** [comment]
i believe i pushed a fix (DDOrderUtil) into master, but i can't see it here. gtg now, i'll checkt later

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
still cannot complete dd_order. Different error:
https://pastebin.com/ArJNHQGy

**Comment by teosarca** [comment]
rolled on w101

**Comment by metas-lc** [comment]
IT
1. create distribution order, add line, complete
=> works, no errors OK
