### ISSUE TITLE
Purchase Order Aggregation

### ISSUE THREAD

**Issue by metas-mk** [metasfresh/metasfresh#4002]
### Is this a bug or feature request?
Feature Request
### What is the current behavior?
Currently, it is not possible to create aggregated Purchase Orders for a vendor in a predefined, automated way.
#### Which are the steps to reproduce?
Open, try and see.
### What is the expected or desired behavior?
For vendors the following settings shall be possible:
- aggregate purchase orders? y/n
- deadline time for purchase orders
- notification to purchasing group of people that a deadline will be reached in x mins (e.g. 30 mins). the notification has a link to purchase order candidates of that vendors for that deadline.

### Note to IT
* full regression on calculating tour delivery days is really required

### Configuration: Business Partner purchase schedule
![image](https://user-images.githubusercontent.com/1244701/39997897-141aff8a-578d-11e8-9cc1-6eb5d5ca973b.png)
![image](https://user-images.githubusercontent.com/1244701/39998977-605ab28e-5790-11e8-8aa1-2e3353d1c4e1.png)

### Configuration: Purchase candidates Due notifications
![image](https://user-images.githubusercontent.com/1244701/39999036-8f1809a0-5790-11e8-8e0d-896b422c86e9.png)

**Comment by cristinamghita** [comment]
@teosarca I checked the issue , thinking that is an import issue.
The problem comes from method org.compiere.util.DB.retrieveValue(ResultSet, int, Class<AT>), which in the previous version supported primitive **int**.
So it was :  ``` else if (returnType.isAssignableFrom(Integer.class) || returnType == int.class) ```
And now is just:  ```else if (returnType.isAssignableFrom(Integer.class))```
Same is double and boolean.
So, I guess that thinking in future, we don't want primitives anymore; so we just need to make sure that the primitive types aren't used.
In case that Lili found, just use Integer in de.metas.pricing.modelvalidator.M_ProductPrice.setSeqNo(I_M_ProductPrice) like ```.aggregate(I_M_ProductPrice.COLUMNNAME_SeqNo, Aggregate.MAX, Integer.class)```

**Comment by teosarca** [comment]
@cristinamghita  weird, don't know how that part was erased.
Yes, we still want to support all those primitives...

**Comment by metas-lc** [comment]
cannot create purchase order from sales order (fails when you start the action)

st:
"org.adempiere.exceptions.AdempiereException: Ihr Test hat einen bisher unentdeckten Fehler offengelegt.
"
1
:
"Bitte leiten Sie diese Meldung an metas weiter:"
2
:
""
3
:
"Assumption failure: schedules is not empty"
4
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)"
5
:
"	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)"
6
:
"	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)"
7
:
"	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)"
8
:
"	at org.adempiere.util.Check.mkEx(Check.java:108)"
9
:
"	at org.adempiere.util.Check.throwOrLogEx(Check.java:119)"
10
:
"	at org.adempiere.util.Check.assume(Check.java:163)"
11
:
"	at org.adempiere.util.Check.assumeNotEmpty(Check.java:342)"
12
:
"	at org.adempiere.util.Check.assumeNotEmpty(Check.java:326)"
13
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository$AllBPPurchaseSchedule.<init>(BPPurchaseScheduleRepository.java:237)"
14
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository$AllBPPurchaseSchedule.<init>(BPPurchaseScheduleRepository.java:226)"
15
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository$AllBPPurchaseSchedule$AllBPPurchaseScheduleBuilder.build(BPPurchaseScheduleRepository.java:233)"
16
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository.retrieveAllBPPurchaseSchedulesByBPartnerId(BPPurchaseScheduleRepository.java:81)"
17
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository.lambda$getByBPartnerIdAndValidFrom$0(BPPurchaseScheduleRepository.java:63)"
18
:
"	at com.google.common.cache.LocalCache$LocalManualCache$1.load(LocalCache.java:5065)"
19
:
"	at com.google.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3716)"
20
:
"	at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2424)"
21
:
"	at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2298)"
22
:
"	at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2211)"
23
:
"	at com.google.common.cache.LocalCache.get(LocalCache.java:4154)"
24
:
"	at com.google.common.cache.LocalCache$LocalManualCache.get(LocalCache.java:5060)"
25
:
"	at org.compiere.util.CCache.get(CCache.java:482)"
26
:
"	at org.compiere.util.CCache.getOrLoad(CCache.java:516)"
27
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository.getByBPartnerIdAndValidFrom(BPPurchaseScheduleRepository.java:63)"
28
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository$$FastClassBySpringCGLIB$$443b5a09.invoke(<generated>)"
29
:
"	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)"
30
:
"	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)"
31
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
32
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
33
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
34
:
"	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)"
35
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleRepository$$EnhancerBySpringCGLIB$$93d6dc1a.getByBPartnerIdAndValidFrom(<generated>)"
36
:
"	at de.metas.purchasecandidate.BPPurchaseScheduleService.getBPPurchaseSchedule(BPPurchaseScheduleService.java:46)"
37
:
"	at de.metas.purchasecandidate.SalesOrderLines.createPurchaseCandidate(SalesOrderLines.java:196)"
38
:
"	at de.metas.purchasecandidate.SalesOrderLines.lambda$createMissingPurchaseCandidates$5(SalesOrderLines.java:183)"
39
:
"	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)"
40
:
"	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)"
41
:
"	at java.util.Iterator.forEachRemaining(Iterator.java:116)"
42
:
"	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)"
43
:
"	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)"
44
:
"	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)"
45
:
"	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)"
46
:
"	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)"
47
:
"	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)"
48
:
"	at de.metas.purchasecandidate.SalesOrderLines.createMissingPurchaseCandidates(SalesOrderLines.java:184)"
49
:
"	at de.metas.purchasecandidate.SalesOrderLines.loadOrCreatePurchaseCandidates0(SalesOrderLines.java:119)"
50
:
"	at de.metas.purchasecandidate.SalesOrderLines.lambda$new$0(SalesOrderLines.java:73)"
51
:
"	at org.adempiere.util.lang.ExtendedMemorizingSupplier.get(ExtendedMemorizingSupplier.java:65)"
52
:
"	at de.metas.purchasecandidate.SalesOrderLines.getSalesOrderLinesWithCandidates(SalesOrderLines.java:247)"
53
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseRowsLoader.load(PurchaseRowsLoader.java:81)"
54
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.SalesOrder2PurchaseViewFactory.lambda$createView$3(SalesOrder2PurchaseViewFactory.java:214)"
55
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseRowsCollection.<init>(PurchaseRowsCollection.java:59)"
56
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseRowsCollection.ofSupplier(PurchaseRowsCollection.java:52)"
57
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseView.<init>(PurchaseView.java:74)"
58
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseView.<init>(PurchaseView.java:56)"
59
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.PurchaseView$PurchaseViewBuilder.build(PurchaseView.java:67)"
60
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.SalesOrder2PurchaseViewFactory.createView(SalesOrder2PurchaseViewFactory.java:231)"
61
:
"	at de.metas.ui.web.order.sales.purchasePlanning.view.SalesOrder2PurchaseViewFactory.createView(SalesOrder2PurchaseViewFactory.java:76)"
62
:
"	at de.metas.ui.web.view.ViewsRepository.createView(ViewsRepository.java:260)"
63
:
"	at sun.reflect.GeneratedMethodAccessor348.invoke(Unknown Source)"
64
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
65
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
66
:
"	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)"
67
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)"
68
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)"
69
:
"	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:136)"
70
:
"	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)"
71
:
"	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)"
72
:
"	at com.sun.proxy.$Proxy142.createView(Unknown Source)"
73
:
"	at de.metas.ui.web.process.adprocess.ADProcessPostProcessService.createResultAction(ADProcessPostProcessService.java:321)"
74
:
"	at de.metas.ui.web.process.adprocess.ADProcessPostProcessService.postProcess(ADProcessPostProcessService.java:102)"
75
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.executeADProcess(ADProcessInstanceController.java:291)"
76
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstanceController.startProcess(ADProcessInstanceController.java:262)"
77
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$null$8(ProcessRestController.java:261)"
78
:
"	at de.metas.ui.web.process.adprocess.ADProcessInstancesRepository.forProcessInstanceWritable(ADProcessInstancesRepository.java:419)"
79
:
"	at de.metas.ui.web.process.ProcessRestController.lambda$startProcess$9(ProcessRestController.java:260)"
80
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.lambda$execute$2(Execution.java:237)"
81
:
"	at de.metas.ui.web.window.controller.Execution$ExecutionBuilder.execute(Execution.java:260)"
82
:
"	at de.metas.ui.web.process.ProcessRestController.startProcess(ProcessRestController.java:259)"
83
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)"
84
:
"	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)"
85
:
"	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)"
86
:
"	at java.lang.reflect.Method.invoke(Method.java:498)"
87
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)"
88
:
"	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)"
89
:
"	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)"
90
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)"
91
:
"	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)"
92
:
"	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)"
93
:
"	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)"
94
:
"	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)"
95
:
"	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)"
96
:
"	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:861)"
97
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:635)"
98
:
"	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)"
99
:
"	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)"

**Comment by metas-lc** [comment]
IT
I. Configs
1. Go to pharma bpartner window, Vendor tab - advanced edit, set Aggregate Purchase Orders on Y

2. Pharma bpartner window, Purchase Schedule tab - add new, set it how you want
=> you have the following fields:
Valid From
Frequency Type (Monthly or Weekly)
Frequency (number)
Day of the Month (number, this field appears only if Frequency Type is set on Monthly)
Reminder Time (min)
Description
Monday (flag)
Monday Preparation Time (readonly. Becomes editable if you set Monday flag on Y)
Tuesday, Tuesday Preparation Time, [...] Sunday, Sunday Preparation Time
Organisation, Client

3. go to Role window, select your current role, go to notifications group add a new one:
Notification group: Purchase Candidates Due
Benachrichtigungs-Art: Notice (or Email+Notice)

II. Testcase
1. Have the configs above for BPartner A
2. Make sure you have a product P1 that has bpartner product A
3. Create a sales order for bpartner B and product P1
4. select the line and run "Create Purchase orders"
5. select your bpartner and another one that does not have Aggregate Purchase Orders on Y, add qtys, press done
=> purchase candidates are created OK
=> isaggregatepo is on Y only for candidates of bpartner A OK
.
currently there is a problem with "Create Purchase orders"
if you run it before completing the order you get purchase order no matter what
if you run it after competing the order, you don't get purchase order 
Didn't get any notifications about purchase candidates. probably because of the same reason
.

III. Regression. Calculating tour delivery days

1. create a new Tour
2. create a new Tour version: add mandatory, isWeekly Y, select a day
3. create a new Tour version line for a bpartner, set location
4. go to tour window - gear / actions, run Generate delivery Days, add some dates:
Error:
Could not initialize class de.metas.calendar.ExcludeWeekendBusinessDayMatcher

<details/>
<summary> stacktrace</summary>
2018-06-14 13:58:04.083 ERROR 635 --- [eryDays-1005183] d.m.t.process.GenerateDeliveryDays       : java.lang.ExceptionInInitializerError

java.lang.ExceptionInInitializerError: null
	at de.metas.adempiere.service.impl.CalendarBL.createBusinessDayMatcherExcluding(CalendarBL.java:213)
	at de.metas.tourplanning.api.impl.TourDAO.createBusinessDayMatcher(TourDAO.java:324)
	at de.metas.tourplanning.api.impl.TourDAO.createDateShifter(TourDAO.java:306)
	at de.metas.tourplanning.api.impl.TourDAO.createDateSequenceGenerator(TourDAO.java:297)
	at de.metas.tourplanning.api.impl.TourDAO.createTourVersionRange(TourDAO.java:280)
	at de.metas.tourplanning.api.impl.TourDAO.retrieveTourVersionRanges(TourDAO.java:226)
	at de.metas.tourplanning.api.impl.DeliveryDayGenerator.generateForTour(DeliveryDayGenerator.java:156)
	at de.metas.tourplanning.api.impl.DeliveryDayGenerator.generate(DeliveryDayGenerator.java:150)
	at de.metas.tourplanning.process.GenerateDeliveryDays.doIt(GenerateDeliveryDays.java:99)
	at de.metas.process.JavaProcess.startProcess(JavaProcess.java:293)
	at de.metas.process.ProcessExecutor.startJavaProcess(ProcessExecutor.java:564)
	at de.metas.process.ProcessExecutor.startJavaOrScriptProcess(ProcessExecutor.java:460)
	at de.metas.process.ProcessExecutor.access$700(ProcessExecutor.java:50)
	at de.metas.process.ProcessExecutor$1.run(ProcessExecutor.java:224)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:145)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$3.call(TrxCallableWrappers.java:135)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:589)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:520)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:506)
	at de.metas.process.ProcessExecutor.executeNow(ProcessExecutor.java:286)
	at de.metas.process.ProcessExecutor.executeSync(ProcessExecutor.java:171)
	at de.metas.process.ProcessExecutor.lambda$executeAsync$0(ProcessExecutor.java:119)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.NullPointerException: excludeWeekendDays
	at de.metas.calendar.ExcludeWeekendBusinessDayMatcher.<init>(ExcludeWeekendBusinessDayMatcher.java:46)
	at de.metas.calendar.ExcludeWeekendBusinessDayMatcher.<init>(ExcludeWeekendBusinessDayMatcher.java:37)
	at de.metas.calendar.ExcludeWeekendBusinessDayMatcher$ExcludeWeekendBusinessDayMatcherBuilder.build(ExcludeWeekendBusinessDayMatcher.java:45)
	at de.metas.calendar.ExcludeWeekendBusinessDayMatcher.<clinit>(ExcludeWeekendBusinessDayMatcher.java:39)
	... 25 common frames omitted
</details>

**Comment by teosarca** [comment]
Quickly checked now and it seems the `Could not initialize class de.metas.calendar.ExcludeWeekendBusinessDayMatcher` issue was fixed.

Moving it back to IT.

**Comment by metas-lc** [comment]
IT
repeated the testcase for Tour
=> works now: delivery days were generated. Both swing and webui OK
.

purchase order from sales order: i still get purchase order when i run the action on an uncompleted sales order. Related with https://github.com/metasfresh/metasfresh/issues/4172
if you create a purchase order from a complete sales order, you get only the candidates.
=> IsAggregatePO is on Y OK 
=> reminderdate is empty OK? (didn't get notification - but not sure if i set it up right)
(reminder date related task https://github.com/metasfresh/metasfresh/issues/4311)
.

**Comment by metas-lc** [comment]
IT3 (to check: step 5 and 7)
1. make configs like in IT1 - for BP A
2. create a sales order - don't complete it. Make sure that the product you are adding has product bp A and B (one without Aggregate Purchase Orders)
3. select the line and run create purchase order
4. add qty to both lines (bp A and B)
5. complete the order
=> got 1 purchase order for bpartner B OK
=> purchase candidates for bpartner A are prepared, isaggregatePO = 'Y' OK
=> reminderdate is null OK? (i didn't get any notifications)
6. create another sales order and make another purchase cand for bp A
7. go to purchase candidates and select those 2 lines, run "Create orders for selection"
=> error in async

<details/>
org.adempiere.exceptions.AdempiereException: No purchase candidates enqueued
Additional parameters:
 I_C_Queue_WorkPackage: X_C_Queue_WorkPackage[C_Queue_WorkPackage_ID=1000956, trxName=null]
 IQueueProcessor: ThreadPoolQueueProcessor{name=C_PurchaseCandidates_GeneratePurchaseOrders, executor=BlockingThreadPoolExecutor [getPoolSize()=1]}
 trxName: <<ThreadInherited>>
	at de.metas.purchasecandidate.async.C_PurchaseCandidates_GeneratePurchaseOrders.getPurchaseCandidates(C_PurchaseCandidates_GeneratePurchaseOrders.java:143)
	at de.metas.purchasecandidate.async.C_PurchaseCandidates_GeneratePurchaseOrders.processWorkPackage(C_PurchaseCandidates_GeneratePurchaseOrders.java:125)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.invokeProcessorAndHandleException(WorkpackageProcessorTask.java:292)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.processWorkpackage(WorkpackageProcessorTask.java:284)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.access$000(WorkpackageProcessorTask.java:84)
	at de.metas.async.processor.impl.WorkpackageProcessorTask$1.run(WorkpackageProcessorTask.java:167)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:103)
	at org.adempiere.ad.trx.api.impl.TrxCallableWrappers$2.call(TrxCallableWrappers.java:93)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call0(AbstractTrxManager.java:775)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.call(AbstractTrxManager.java:688)
	at org.adempiere.ad.trx.api.impl.AbstractTrxManager.run(AbstractTrxManager.java:596)
	at de.metas.async.processor.impl.WorkpackageProcessorTask.run(WorkpackageProcessorTask.java:157)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at Thread.run(Thread.java:748)
</details>
